import {
  Project,
  Task,
  DailyLog,
  DrawingDocument,
  PunchItem,
  RFI,
  ChangeOrder,
  BudgetLineItem,
  Profile,
} from "@/types/database";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "user-1",
    email: "sarah.connor@apexconstruction.com",
    full_name: "Sarah Connor",
    role: "project_manager",
    company_name: "Apex Builders Group",
    phone: "+1 (555) 019-2834",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    created_at: "2026-01-10T08:00:00Z",
  },
  {
    id: "user-2",
    email: "marcus.vance@apexconstruction.com",
    full_name: "Marcus Vance",
    role: "superintendent",
    company_name: "Apex Builders Group",
    phone: "+1 (555) 014-9921",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    created_at: "2026-01-12T08:00:00Z",
  },
  {
    id: "user-3",
    email: "elena.rostova@volticelectrical.com",
    full_name: "Elena Rostova",
    role: "subcontractor",
    company_name: "Voltic Electrical Inc.",
    phone: "+1 (555) 018-7733",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    created_at: "2026-01-15T08:00:00Z",
  },
  {
    id: "user-4",
    email: "david.chen@skylinecorp.com",
    full_name: "David Chen",
    role: "client",
    company_name: "Skyline Commercial Holdings",
    phone: "+1 (555) 011-4455",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    created_at: "2026-01-18T08:00:00Z",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "prj-1",
    code: "PRJ-2026-001",
    name: "Skyline Heights Tower (42-Story Mixed Use)",
    description: "42-story luxury residential tower with ground floor retail, underground parking, and rooftop terrace.",
    address: "742 Evergreen Terrace",
    city: "Seattle",
    state: "WA",
    zip_code: "98101",
    client_name: "Skyline Commercial Holdings",
    client_email: "david.chen@skylinecorp.com",
    status: "in_progress",
    budget: 45000000,
    spent: 28350000,
    start_date: "2025-06-01",
    target_completion_date: "2027-03-30",
    cover_image_url: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80",
    created_at: "2025-05-15T00:00:00Z",
  },
  {
    id: "prj-2",
    code: "PRJ-2026-002",
    name: "Cascade Medical Center Wing Expansion",
    description: "State-of-the-art 3-story surgical ward addition, including 12 ORs and ICU units.",
    address: "1200 Health Parkway",
    city: "Bellevue",
    state: "WA",
    zip_code: "98004",
    client_name: "Cascade Health Network",
    client_email: "facilities@cascadehealth.org",
    status: "in_progress",
    budget: 18500000,
    spent: 12200000,
    start_date: "2025-09-15",
    target_completion_date: "2026-11-20",
    cover_image_url: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&auto=format&fit=crop&q=80",
    created_at: "2025-08-20T00:00:00Z",
  },
  {
    id: "prj-3",
    code: "PRJ-2026-003",
    name: "Harborview Logistics & Distribution Hub",
    description: "250,000 sq ft industrial warehouse with 36 loading docks and solar array roof integration.",
    address: "880 Port Way",
    city: "Tacoma",
    state: "WA",
    zip_code: "98421",
    client_name: "Pacific Freight Logistics",
    client_email: "operations@pacificfreight.com",
    status: "planning",
    budget: 24000000,
    spent: 1500000,
    start_date: "2026-04-01",
    target_completion_date: "2027-08-15",
    cover_image_url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80",
    created_at: "2026-01-05T00:00:00Z",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    project_id: "prj-1",
    title: "Level 18 Post-Tension Slab Pour",
    description: "Coordinate concrete pump trucks and conduct pre-pour rebar inspection with structural engineer.",
    status: "in_progress",
    priority: "critical",
    assigned_to: "user-2",
    trade_category: "Concrete",
    start_date: "2026-08-24",
    due_date: "2026-08-27",
    order_index: 0,
    created_at: "2026-08-20T00:00:00Z",
  },
  {
    id: "task-2",
    project_id: "prj-1",
    title: "Level 14 Curtain Wall Glazing Installation",
    description: "Install South-facing insulated glass panels and test weather sealing.",
    status: "todo",
    priority: "high",
    assigned_to: "user-3",
    trade_category: "Glazing",
    start_date: "2026-08-28",
    due_date: "2026-09-05",
    order_index: 1,
    created_at: "2026-08-20T00:00:00Z",
  },
  {
    id: "task-3",
    project_id: "prj-1",
    title: "Level 10 MEP Rough-In Inspection",
    description: "City mechanical and electrical rough-in inspection signoff.",
    status: "review",
    priority: "high",
    assigned_to: "user-1",
    trade_category: "MEP",
    start_date: "2026-08-21",
    due_date: "2026-08-26",
    order_index: 2,
    created_at: "2026-08-18T00:00:00Z",
  },
  {
    id: "task-4",
    project_id: "prj-1",
    title: "Level 8 Drywall & Taping",
    description: "Complete Level 4 drywall finish across units 801-808.",
    status: "done",
    priority: "medium",
    assigned_to: "user-2",
    trade_category: "Finishes",
    start_date: "2026-08-10",
    due_date: "2026-08-22",
    completed_at: "2026-08-22T16:00:00Z",
    order_index: 3,
    created_at: "2026-08-08T00:00:00Z",
  },
  {
    id: "task-5",
    project_id: "prj-1",
    title: "Elevator Shaft 2 Guide Rail Alignment",
    description: "High-speed traction elevator guide rail laser alignment.",
    status: "todo",
    priority: "medium",
    assigned_to: "user-3",
    trade_category: "Elevator",
    start_date: "2026-08-30",
    due_date: "2026-09-10",
    order_index: 4,
    created_at: "2026-08-22T00:00:00Z",
  },
];

export const MOCK_DAILY_LOGS: DailyLog[] = [
  {
    id: "log-1",
    project_id: "prj-1",
    log_date: "2026-08-25",
    author_id: "user-2",
    weather_condition: "Clear / Sunny",
    temp_high: 78,
    temp_low: 58,
    site_conditions: "Dry and clear. Wind under 6mph. Crane 1 & 2 fully operational.",
    work_performed: "Level 18 slab formwork 95% complete. Rebar tie-off ongoing on west wing. MEP rough-in continuing on Levels 11 & 12. Fire sprinkler piping pressure test passed on Level 9.",
    delays_notes: "Minor 30-minute delay in morning concrete truck staging due to 4th Ave traffic.",
    safety_incidents: "Zero incidents. Morning toolbox talk topic: Fall protection tie-off at perimeter leading edges.",
    visitors_log: "City Structural Inspector (John Miller) on site from 10:30 AM to 11:45 AM.",
    crews: [
      { id: "c-1", daily_log_id: "log-1", contractor_name: "Titan Concrete Works", trade: "Concrete & Rebar", worker_count: 24, hours_worked: 8 },
      { id: "c-2", daily_log_id: "log-1", contractor_name: "Voltic Electrical Inc.", trade: "Electrical", worker_count: 14, hours_worked: 8 },
      { id: "c-3", daily_log_id: "log-1", contractor_name: "Cascade Mechanical & HVAC", trade: "HVAC / Plumbing", worker_count: 18, hours_worked: 8 },
      { id: "c-4", daily_log_id: "log-1", contractor_name: "Apex Framing & Drywall", trade: "Interior Drywall", worker_count: 16, hours_worked: 8 },
    ],
    created_at: "2026-08-25T16:30:00Z",
  },
  {
    id: "log-2",
    project_id: "prj-1",
    log_date: "2026-08-24",
    author_id: "user-2",
    weather_condition: "Partly Cloudy",
    temp_high: 72,
    temp_low: 55,
    site_conditions: "Excellent site conditions. Good air quality.",
    work_performed: "Level 17 post-tension cables stressed and grouted. Shoring inspection completed. Framing underway on Level 13.",
    delays_notes: "None.",
    safety_incidents: "Zero incidents. PPE compliance audit 100%.",
    visitors_log: "Architectural representative review of exterior sample mockups.",
    crews: [
      { id: "c-5", daily_log_id: "log-2", contractor_name: "Titan Concrete Works", trade: "Concrete", worker_count: 22, hours_worked: 8 },
      { id: "c-6", daily_log_id: "log-2", contractor_name: "Voltic Electrical Inc.", trade: "Electrical", worker_count: 12, hours_worked: 8 },
    ],
    created_at: "2026-08-24T17:00:00Z",
  },
];

export const MOCK_DRAWINGS: DrawingDocument[] = [
  {
    id: "doc-1",
    project_id: "prj-1",
    title: "Overall Floor Plan - Level 18 to 25 Typical",
    sheet_number: "A-118",
    category: "architectural",
    version: 3,
    file_url: "https://example.com/blueprints/A-118-Rev3.pdf",
    file_size_bytes: 14500000,
    storage_path: "blueprints/prj-1/A-118-Rev3.pdf",
    description: "Updated with revised corridor egress dimensions per City Building Department review comments.",
    created_at: "2026-08-15T00:00:00Z",
  },
  {
    id: "doc-2",
    project_id: "prj-1",
    title: "Structural Columns & Post-Tension Details",
    sheet_number: "S-204",
    category: "structural",
    version: 2,
    file_url: "https://example.com/blueprints/S-204-Rev2.pdf",
    file_size_bytes: 22100000,
    storage_path: "blueprints/prj-1/S-204-Rev2.pdf",
    description: "Post-tension tendon layout and shear reinforcement schedules.",
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "doc-3",
    project_id: "prj-1",
    title: "HVAC Duct Routing & Risers",
    sheet_number: "M-301",
    category: "mep",
    version: 1,
    file_url: "https://example.com/blueprints/M-301-Rev1.pdf",
    file_size_bytes: 18700000,
    storage_path: "blueprints/prj-1/M-301-Rev1.pdf",
    description: "Main mechanical riser shafts and damper locations.",
    created_at: "2026-07-10T00:00:00Z",
  },
  {
    id: "doc-4",
    project_id: "prj-1",
    title: "City Building & Structural Permit Set (Stamped)",
    sheet_number: "PERM-01",
    category: "permits",
    version: 1,
    file_url: "https://example.com/blueprints/Permit-Set.pdf",
    file_size_bytes: 45000000,
    storage_path: "blueprints/prj-1/Permit-Set.pdf",
    description: "Official stamped permit documentation from Department of Construction & Inspections.",
    created_at: "2025-05-20T00:00:00Z",
  },
];

export const MOCK_PUNCH_ITEMS: PunchItem[] = [
  {
    id: "punch-1",
    project_id: "prj-1",
    item_number: 101,
    title: "Fire damper access panel clearance blocked by conduit",
    description: "Conduit bundle on ceiling grid restricts full 90-degree opening of FD-14B access door.",
    location: "Level 14 - Corridor North / Room 1402",
    status: "open",
    severity: "major",
    trade: "Electrical / HVAC",
    assigned_to: "user-3",
    reported_by: "user-2",
    photo_urls: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80",
    ],
    created_at: "2026-08-23T11:00:00Z",
  },
  {
    id: "punch-2",
    project_id: "prj-1",
    item_number: 102,
    title: "Scuffed paint and drywall dent near service elevator",
    description: "Scuff marks from material pallet cart during drywall delivery.",
    location: "Level 9 - Freight Elevator Vestibule",
    status: "ready_for_inspection",
    severity: "cosmetic",
    trade: "Painting / Drywall",
    assigned_to: "user-2",
    reported_by: "user-1",
    photo_urls: [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80",
    ],
    resolution_notes: "Patched, sanded, and repainted with two coats of SW 7005 Pure White.",
    created_at: "2026-08-21T09:30:00Z",
  },
  {
    id: "punch-3",
    project_id: "prj-1",
    item_number: 103,
    title: "Window seal gap causing draft",
    description: "Silicone weatherseal incomplete on lower left frame mullion.",
    location: "Level 12 - Unit 1204 Balcony Door",
    status: "approved",
    severity: "minor",
    trade: "Glazing",
    assigned_to: "user-3",
    reported_by: "user-2",
    photo_urls: [],
    resolution_notes: "Re-beaded with Dow Corning 795 weatherproofing sealant and water-spray tested.",
    resolved_at: "2026-08-24T15:00:00Z",
    created_at: "2026-08-19T14:00:00Z",
  },
];

export const MOCK_RFIS: RFI[] = [
  {
    id: "rfi-1",
    project_id: "prj-1",
    rfi_number: 44,
    subject: "Clash between Plumbing Drain and Structural Beam B-18",
    question: "Plumbing 4-inch sanitary line on Level 18 conflicts with 24-inch deep steel beam bottom flange. Please advise if sleeve can penetrate web or if pipe offset is required.",
    suggested_solution: "Provide 5-inch sleeved core penetration through beam neutral axis per typical detail S-501.",
    status: "answered",
    impact_cost: false,
    impact_days: 0,
    cost_estimate: 0,
    assigned_to: "user-1",
    submitted_by: "user-2",
    official_answer: "Approved to core web within 36 inches of support column centerline. Reinforcing collar plate not required per engineer calculation memo #E-89.",
    due_date: "2026-08-26",
    created_at: "2026-08-22T08:00:00Z",
  },
  {
    id: "rfi-2",
    project_id: "prj-1",
    rfi_number: 45,
    subject: "Balcony Railing Glass Thickness Clarification",
    question: "Spec section 088000 calls for 1/2-inch laminated glass, but architectural detail A-602 note specifies 5/8-inch tempered. Please confirm required specification.",
    suggested_solution: "Confirm 1/2-inch laminated glass meets 2026 IBC wind load criteria.",
    status: "submitted",
    impact_cost: true,
    impact_days: 3,
    cost_estimate: 8500,
    assigned_to: "user-4",
    submitted_by: "user-3",
    due_date: "2026-08-29",
    created_at: "2026-08-24T10:00:00Z",
  },
];

export const MOCK_CHANGE_ORDERS: ChangeOrder[] = [
  {
    id: "co-1",
    project_id: "prj-1",
    co_number: 7,
    title: "Upgrade Level 42 Penthouse Smart Home Automation",
    description: "Client requested Lutron Homeworks QSX lighting and automated motorized shading pre-wire across units PH-1 and PH-2.",
    status: "approved",
    amount: 145000,
    schedule_impact_days: 5,
    reason: "Owner Scope Addition",
    requested_by: "user-4",
    approved_by: "user-1",
    approved_at: "2026-08-15T00:00:00Z",
    created_at: "2026-08-10T00:00:00Z",
  },
  {
    id: "co-2",
    project_id: "prj-1",
    co_number: 8,
    title: "Subsurface Rock Excavation Contingency",
    description: "Encountered unexpected basalt bedrock stratum during stormwater retention tank excavation.",
    status: "submitted",
    amount: 88500,
    schedule_impact_days: 4,
    reason: "Unforeseen Site Condition",
    requested_by: "user-2",
    created_at: "2026-08-23T00:00:00Z",
  },
];

export const MOCK_BUDGET: BudgetLineItem[] = [
  {
    id: "b-1",
    project_id: "prj-1",
    cost_code: "02-0000",
    category: "Site Work & Foundations",
    description: "Excavation, shoring, piling, and earthwork",
    original_budget: 4800000,
    approved_changes: 180000,
    committed_costs: 4980000,
    actual_spent: 4980000,
  },
  {
    id: "b-2",
    project_id: "prj-1",
    cost_code: "03-0000",
    category: "Concrete & Superstructure",
    description: "Post-tension slabs, shear walls, and columns",
    original_budget: 14500000,
    approved_changes: 250000,
    committed_costs: 14750000,
    actual_spent: 11200000,
  },
  {
    id: "b-3",
    project_id: "prj-1",
    cost_code: "08-0000",
    category: "Exterior Enclosure & Glazing",
    description: "Curtain wall, window wall, and terrace doors",
    original_budget: 8200000,
    approved_changes: 0,
    committed_costs: 8200000,
    actual_spent: 4100000,
  },
  {
    id: "b-4",
    project_id: "prj-1",
    cost_code: "21-2600",
    category: "MEP Systems (Mechanical, Electrical, Plumbing)",
    description: "HVAC risers, main switchgear, water distribution, sprinklers",
    original_budget: 11000000,
    approved_changes: 320000,
    committed_costs: 11320000,
    actual_spent: 6200000,
  },
  {
    id: "b-5",
    project_id: "prj-1",
    cost_code: "09-0000",
    category: "Interior Finishes & Millwork",
    description: "Drywall, flooring, paint, cabinetry, fixtures",
    original_budget: 6500000,
    approved_changes: 145000,
    committed_costs: 5800000,
    actual_spent: 1870000,
  },
];
